/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_851236_7_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_851236_2[] = { "N", "lateral", "onda", "para_cima" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_851236_6_axes[] = { 0, 1, 2, 3, 4, 5 };
const uint32_t ei_dsp_config_851236_6_axes_size = 6;
ei_dsp_config_spectral_analysis_t ei_dsp_config_851236_6 = {
    6, // uint32_t blockId
    4, // int implementationVersion
    6, // int length of axes
    1.0f, // float scale-axes
    1, // int input-decimation-ratio
    "none", // select filter-type
    3.0f, // float filter-cutoff
    6, // int filter-order
    "FFT", // select analysis-type
    16, // int fft-length
    3, // int spectral-peaks-count
    0.1f, // float spectral-peaks-threshold
    "0.1, 0.5, 1.0, 2.0, 5.0", // string spectral-power-edges
    true, // boolean do-log
    true, // boolean do-fft-overlap
    1, // int wavelet-level
    "db4", // select wavelet
    false // boolean extra-low-freq
};

const float ei_dn_standard_scaler_mean_851236_6[78] = { 2.245094403728015, 0.009236436311362518, -0.9637393774464726, 1.8241751541694005, 2.579801567726665, -0.0685480965508355, -0.6131948232650757, -0.8553205364280276, -0.9652866921905014, -1.1218772733409423, -1.1429925991429224, -1.1599874146696594, -1.2021614495250914, 2.5725793462867537, 0.3877308029267523, -0.3049762273828189, 1.3702999552090962, 1.109519875711865, 0.06256484985351562, -0.5605609251393212, -0.7426779833104875, -0.9740867159432836, -1.0182974172704335, -1.2194854675067797, -1.1551104386647542, -1.1453993022441864, 4.265352738607261, 0.14699984341859818, -0.6971886952718099, 1.913747787475586, 2.344425572289361, 0.28763413429260254, -0.16977312829759386, -0.48798773686091107, -0.5917358530892266, -0.6265983713997735, -0.7397897011703916, -0.8713060650560591, -0.6925110220909119, 18.711812357935642, 0.12101512319511837, -0.37591072275406784, 1.461788621213701, 0.8024289053347375, 1.7947889433966742, 1.2210858530468411, 1.113986955748664, 0.8785518805185953, 0.7178547647264268, 0.6020645035637749, 0.6586611933178372, 0.5607684718237983, 82.490888984253, -0.1332205923067199, -0.7810168605711725, 1.6877200222677655, 1.9792274799611833, 2.48874741130405, 1.97917636235555, 1.6929359171125624, 1.5859991709391277, 1.5716522004869249, 1.4558424419826932, 1.391196158197191, 1.462779508696662, 54.058003801438545, -0.04688069596886635, -0.9698794715934329, 1.549458106358846, 1.827987680832545, 2.248993396759033, 1.5741928153567843, 1.366392559475369, 1.2859651115205553, 1.2013220654593573, 1.080451144112481, 1.0594468381669786, 1.0345563093821208 };
const float ei_dn_standard_scaler_scale_851236_6[78] = { 0.5586116736743426, 3.5601816771552324, 1.778882013651263, 1.3764178096189044, 0.7086132065644019, 0.3940675632726193, 0.4656175419113332, 0.4983291565897641, 0.5259125389385869, 0.5195958952513131, 0.5469053428131113, 0.5534293207135003, 0.5680901491535806, 0.4025074551783473, 1.5630740366606897, 1.6366563179459885, 1.2383621151255084, 0.6425576790812934, 0.3744624301292386, 0.44429867549099616, 0.49750197373281807, 0.50862379651831, 0.5203131889348972, 0.5255312163057989, 0.550223856300058, 0.5461422539885404, 0.31278242539634277, 2.623046134553127, 2.9830639431205572, 2.0944180604472185, 0.6473417015408601, 0.34917699293967636, 0.40547931892001915, 0.4385816776120169, 0.4576711148418347, 0.4937476473254491, 0.47752145252486716, 0.49366764949676306, 0.5187699592093669, 0.05649604921065873, 2.925205495104818, 1.472957361902795, 2.15017583980425, 0.7085213996815483, 0.3722121282085237, 0.4450544460121661, 0.4647231364016016, 0.48994924816350854, 0.47247106821463525, 0.5346545824475253, 0.5671406050727018, 0.5045818963694582, 0.016012429377679993, 2.1367865660459184, 1.2660205329787135, 1.2026546773954199, 0.5049147680810527, 0.2978062504836324, 0.33479641697204643, 0.35291024373546004, 0.3707300868286285, 0.3962377409964527, 0.39615630459245127, 0.4075598028468315, 0.4054188743217588, 0.019758546631912788, 2.8105194505817517, 1.8377033024555463, 1.066067665500701, 0.48674833286499936, 0.32153677049360935, 0.3393732935255706, 0.3859034677728347, 0.3942440563263557, 0.41404577233416057, 0.40410790436004157, 0.4187252150775213, 0.4055007011116904 };
const float ei_dn_standard_scaler_var_851236_6[78] = { 3.2046454338675576, 0.07889612596223611, 0.31601355538772335, 0.5278365179754478, 1.9915055258611143, 6.439596017816014, 4.612552607383734, 4.026868096576428, 3.6155381548295042, 3.7039795217458282, 3.3433024595006837, 3.2649435082236886, 3.098599759957815, 6.172372711946172, 0.40929920523791996, 0.3733232322717315, 0.6520857135552051, 2.4220090621115262, 7.131542869696672, 5.065822433419672, 4.040269954568519, 3.865508650389665, 3.693774092259561, 3.620786888564547, 3.3030957811441612, 3.352651741902541, 10.221516030641318, 0.14534099927353822, 0.1123763377085023, 0.22796766535826565, 2.386342796640761, 8.201792143526644, 6.082226419193182, 5.198751170174797, 4.774116283879091, 4.101945836430128, 4.385450629303275, 4.103275367941423, 3.715783156302709, 313.3024874681548, 0.11686574684285686, 0.46091373410305203, 0.21629777136910958, 1.9920216592057898, 7.218034603209727, 5.048631959214242, 4.630324317466907, 4.165794179678979, 4.479706497947028, 3.4982707038223264, 3.1089842046434155, 3.9276851862726483, 3900.1880325766397, 0.21901694194281296, 0.6239050505654146, 0.6913820669357976, 3.922508136965293, 11.275411035234532, 8.9215106250577, 8.029185115823658, 7.27586000511211, 6.369250384616237, 6.37186926082232, 6.020288629269619, 6.084040173616543, 2561.474327209834, 0.1265979897386649, 0.296107364193651, 0.8798942056254389, 4.220763853212186, 9.672499349482564, 8.68249763443834, 6.714947748046721, 6.433831621134106, 5.833151965499068, 6.123578778641863, 5.703504274503371, 6.081585000315727 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_851236_6 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_851236_6,
    .mean_data_len = 78,
    .scale_data = (float *)ei_dn_standard_scaler_scale_851236_6,
    .scale_data_len = 78,
    .var_data = (float *)ei_dn_standard_scaler_var_851236_6,
    .var_data_len = 78
};
ei_data_normalization_t ei_data_normalization_config_851236_6 = {
    (void *) &ei_data_normalization_standard_scaler_config_851236_6, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_851236_2_size = 1;
ei_model_dsp_t ei_dsp_blocks_851236_2[ei_dsp_blocks_851236_2_size] = {
    { // DSP block 6
        6,
        78, // output size
        &extract_spectral_analysis_features, // DSP function pointer
        (void*)&ei_dsp_config_851236_6, // pointer to config struct
        ei_dsp_config_851236_6_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_851236_6_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_851236_6, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_851236_7 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_851236_7_init,
    .model_invoke = &tflite_learn_851236_7_invoke,
    .model_reset = &tflite_learn_851236_7_reset,
    .model_input = &tflite_learn_851236_7_input,
    .model_output = &tflite_learn_851236_7_output,
};

const uint8_t ei_output_tensors_indices_851236_7[1] = { 0 };
const uint8_t ei_output_tensors_size_851236_7 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_851236_7 = {
    .implementation_version = 1,
    .block_id = 7,
    .output_tensors_indices = ei_output_tensors_indices_851236_7,
    .output_tensors_size = ei_output_tensors_size_851236_7,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_851236_7,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_851236_2_size = 1;
const uint32_t ei_learning_block_851236_7_inputs[1] = { 6 };
const uint8_t ei_learning_block_851236_7_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_851236_2[ei_learning_blocks_851236_2_size] = {
    {
        7,
        &run_nn_inference,
        (void*)&ei_learning_block_config_851236_7,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_851236_7_inputs,
        ei_learning_block_851236_7_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_851236_7 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_851236_2_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_851236_2[ei_postprocessing_blocks_851236_2_size] = {
    {
        .block_id = 7,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_851236_7,
        .input_block_id = 7
    },
};

const uint8_t freeform_outputs_851236_2_size = 0;

uint32_t *freeform_outputs_851236_2 = nullptr;

const ei_impulse_t impulse_851236_2 = {
    .project_id = 851236,
    .project_owner = "profnorisjunior",
    .project_name = "XIAO nRF52840 _ 1",
    .impulse_id = 2,
    .impulse_name = "Impulse #2",
    .deploy_version = 1,

    .nn_input_frame_size = 78,
    .raw_sample_count = 50,
    .raw_samples_per_frame = 6,
    .dsp_input_frame_size = 50 * 6,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 20,
    .frequency = 50,

    .dsp_blocks_size = ei_dsp_blocks_851236_2_size,
    .dsp_blocks = ei_dsp_blocks_851236_2,

    .learning_blocks_size = ei_learning_blocks_851236_2_size,
    .learning_blocks = ei_learning_blocks_851236_2,

    .postprocessing_blocks_size = ei_postprocessing_blocks_851236_2_size,
    .postprocessing_blocks = ei_postprocessing_blocks_851236_2,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "Accel_X + Accel_Y + Accel_Z + Gyro_X + Gyro_Y + GyroZ",
    .slice_size = (50/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 4,
    .categories = ei_classifier_inferencing_categories_851236_2,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_851236_2_size,
    .freeform_outputs = freeform_outputs_851236_2
};

ei_impulse_handle_t impulse_handle_851236_2 = ei_impulse_handle_t( &impulse_851236_2 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_851236_2;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_851236_2;
const auto ei_dsp_blocks_size = ei_dsp_blocks_851236_2_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_851236_2;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
