services:
  postgres:
    image: postgres:15
    restart: always
    user: "999:999"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-n8n}
      POSTGRES_USER: ${POSTGRES_USER:-n8nuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - n8n_backend
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-n8nuser} -d ${POSTGRES_DB:-n8n}']
      interval: 5s
      timeout: 5s
      retries: 5

  n8n:
    image: n8nio/n8n:latest
    restart: always
    user: "1000:1000"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB:-n8n}
      DB_POSTGRESDB_USER: ${POSTGRES_USER:-n8nuser}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
      # Configuração para acesso por IP público
      N8N_HOST: ${AWS_PUBLIC_IP}
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      N8N_LISTEN_ADDRESS: 0.0.0.0
      WEBHOOK_URL: http://${AWS_PUBLIC_IP}:5678
      GENERIC_TIMEZONE: America/Sao_Paulo
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_LOG_LEVEL: info
      # Configurações para desenvolvimento/ensino
      N8N_RUNNERS_ENABLED: true
      N8N_BLOCK_ENV_ACCESS_IN_NODE: false
      N8N_DISABLE_PRODUCTION_MAIN_PROCESS: true
      N8N_SECURE_COOKIE: false
    ports:
      - '${N8N_PORT}:5678'  # Expõe para qualquer interface
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - n8n_backend
    depends_on:
      postgres:
        condition: service_healthy

networks:
  n8n_backend:
    driver: bridge