services:
  node-red:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: NorisNodeRED
    ports:
      - "1880:1880"
    environment:
      - TZ=America/Sao_Paulo
    restart: unless-stopped